Alexandra Ryder, E.I.T.

Electrical Engineer

Philadelphia, PA - Email me on Indeed: indeed.com/r/42b263d976f56568

WORK EXPERIENCE

Electrical Engineer
Pepco Holdings, Inc  -  Newark, DE - May 2012 to Present

Member of Transmission Planning team in the Asset Strategy and Planning department
• Company representative to PJM; the regional transmission organization
• Company representative to Reliability First Corporation (RFC); the regional enforcer of reliability standards
under the North American Electric Reliability Corporation (NERC)
• Determine, communicate, and maintain transmission circuit ratings and associated database
• Create and maintain transmission system cases to be analyzed
• Perform various types of system analysis including thermal and voltage studies
• Develop and sponsor transmission level projects to mitigate potential system violations
• Work with prospective and existing transmission level electric customers
• Participate in storm duty when necessary
• Organized company job shadow event for 24 high school students

Electrical Engineer Intern
Pepco Holdings, Inc  -  Newark, DE - May 2011 to August 2011

Create and update electric system drawings using various types of software
• Perform thermal and voltage system analysis
• Work with multiple departments to collect project details
• Make recommendations for placement of transmission system equipment
• Collect and input project information to aid company in the asset distribution process
• Improved procedure for updating the impedance and rating database for transmission
circuits

Math and Engineering Tutor
Pennsylvania State University  -  Harrisburg, PA - September 2010 to December 2010

September 2010 - December 2010
• Tutor students in subjects including Calculus, Algebra, Computer Programming, and
Computer Engineering

EDUCATION

Bachelor of Science in Electrical Engineering
Pennsylvania State University - Harrisburg, PA
2012

ADDITIONAL INFORMATION

Computer Skills
Adobe, Bentley MicroStation, CorelDraw, IBM Lotus Notes, Matlab, Microsoft Access,
Microsoft Excel, Microsoft PowerPoint, Microsoft Visio, Microsoft Word, Osisoft Pi, Power

System Simulator for Engineering (PSSE), Primavera, SAP, ZTable Database

