HIEP LE, E.I.T

Electrical Engineer - Jacobs Engineering

Philadelphia, PA - Email me on Indeed: indeed.com/r/e8713ca106502e59

WORK EXPERIENCE

Electrical Engineer
Jacobs Engineering  -  Conshohocken, PA - January 2013 to Present

Apply sound and diversified knowledge of engineering principles and practices in lighting and building power
applications with projects that deal with pharmaceutical facilities
• Incorporate lighting control system design for energy efficient facility. Includes sensor layout, panel
placement, and modification of control wiring diagram
• Use of lighting analysis software for design 3D modeling and calculations
• Developed strong teamwork, communication, and coordination skills

Electrical Engineer
Bonnett Associates Incorporated  -  Eddystone, PA - June 2009 to December 2012

Apply sound and diversified knowledge of engineering principles and practices in lighting, building power, and
fire alarm system applications with projects that deal with both existing and new educational facilities
• Meet with clients to plan, design, and discuss the scope of the project
• On site survey to gain an accurate and current understanding of the existing facility
• Drafting and design detailed drawings based on information, rough sketches, specifications, calculations and
estimates with AutoCAD, Visual, and other designing software
• Review construction documents base on design specifications, details, and construction drawings
• Developed strong teamwork, communication, and coordination skills while working with other engineers and
architects

Sales Personal
E. Frank Hopkins  -  Philadelphia, PA - 2007 to 2008

Help customers improve buying decisions by sharing product information
• High degree of positive customer communication and interaction at all times

Water Meter Installer
VSI Meter Services Incorporated  -  Philadelphia, PA - July 2005 to August 2005

Specializes in meter reading, installation, and maintenance
• Provide superior customer service with professionalism

ACTIVITIES: Member of Delaware Valley Green Building Council
Member of Pi Delta Psi Fraternity Tau Chapter
In my spare time I enjoy playing sports, watching poker, and traveling.

EDUCATION

Bachelor of Science in Electrical Engineering
The Pennsylvania State University - University Park, PA
May 2009

ADDITIONAL INFORMATION

COMPUTER SKILLS AutoCAD: Computer aided design/drafting software application.
Visual Professional Edition: Comprehensive lighting analysis software designed
for interior and exterior applications.
COMcheck: Software use to demonstrate energy code compliance in the design
and construction of commercial and high-rise residential building.
Microsoft Office (Word, Excel, PowerPoint)

