Huchen E.I.T

Traffic Engineer/Planner Intern - Delaware Valley Regional Planning Commission

Philadelphia, PA - Email me on Indeed: indeed.com/r/Huchen-E-I-T/1cc14993c2ec7d3c

Dear HR manager and transportation engineering team,
I  am  glad  to  hear  from  you  needing  a  dedicated  Transportation  Engineer  with  some  professional  working
experience and education. I am ready to become an immediate contributor to your team. The following are the
highlights of my qualifications and accomplishments:
〓 15-month experience in corridor planning studies in Delaware Valley Regional Planning Commission
〓 four-month experience of participating in the activities of NJDOT program ( video analyst and field data
collector)
〓 Two-year experience as a traffic engineer experience in China.
〓 EIT license from Maine, No 6913 (Subject: Civil Engineering)
〓  Education:  Master  of  Science  in  Transportation  (GPA  3.8),  Bachelor  of  Engineering  in  Micro-
electronics(GPA:2.75)
〓 Key Courses: 
Highway Capacity Studies (A) Traffic Control (B) 
Urban System Engineering (A) Public Transportation Operation & Tech (A) 
Construction Management (A) Land Use Planning (B) 
Construction Cost Estimate (A) Project Management (A) 
Introduction of Urban Transportation Planning (A) 
Mutil-modal Freight Transportation Systems Analysis (A)
〓 In-depth knowledge of traffic planning (trip generation, distribution, assignment, LOS, Density, MUTCD,
TCQSM,  HCM,  ITS,  etc.),  and  land  use  planning  (demographics,  zoning,  smart  growth,  new  urbanism,
sustainability, etc.) 
〓 Experience of using Traffic modeling software such as VISSIM, Synchro, and HCS 
〓 Strong ability to prepare traffic signal design and traffic control plans using AutoCAD
〓 Geographic information systems skills: ArcMap
〓 Preparation of presentation materials for meetings in PennDOT and helping manager answer the questions
from experts in PennDOT and Consulting firms.
〓 Roundabout design (AutoCAD) based on NCHRP report 672 Synthesis 488 and HCM2010
〓 Achievement of 4 projects related to Transportation Planning/Engineering field
My strong initiative and skills combined with the projects allow me to join and contribute to your team. I sincerely
hope your team gives me an opportunity to discuss with how my skills and strengths fit your need. I have work
sample (graphics and technical reports) to show if there is an interview. 
Sincerely,
Huchen Liao
Willing to relocate: Anywhere
Authorized to work in the US for any employer

WORK EXPERIENCE

Traffic Engineer/Planner Intern
Delaware Valley Regional Planning Commission  -  Philadelphia, PA - February 2015 to Present

o Building VISSIM traffic modeling networks for projects in the Philadelphia region 
o Calibrating traffic models by synthesizing raw data to current typical weekday volume conditions, and dis-
aggregating volumes to 15-minute intervals for the mainline, ramp, and study intersection network. 

o Using traffic modeling software to compare data such as volume, speed, driver fuel cost and queue length
to justify new roadway designs 
o Gathering volume and signal timings data in the field. 
o Inputting signal timing data and optimizing traffic networks in Synchro
o Designing projects in AutoCAD and creating maps using ArcMap
o Synthesizing raw date from SEPTA (public transit agency) to calculate the dwell time for bus stops based
on guideline from the Transit Capacity and Quality of Service Manual (TCQSM). 
o Transit service analysis using VISSIM traffic modeling software, which involved evaluating Transit Signal
Priority (TSP) and Business Access & Transit (BAT) lanes
o Analyzing crash data and writing crash reports
o Forecasting future scenario traffic trip generation using the ITE Trip Generation Manual and growth rate
assumptions from PennDOT or NJDOT 
o Roundabout design based on NCHRP report 672 Synthesis 488 and HCM2010

Transportation Engineer
Guangdong Metallurgical and Architectural Design Institute - June 2014 to July 2014

June 2014 - July 2014 (2 months)
o Perform data collection on seat-belt usage of New Jersey of drivers and passengers.

4. Transportation Engineer at Guangdong Metallurgical and Architectural Design Institute
September 2010 - August 2012
o Pavement and markings design based on Chinese traffic laws (similar as MUTCD) using
AutoCAD

EDUCATION

Master's in Transportation Engineering
1. New Jersey Institute of Technology
2014 to 2015

Bachelor of Engineering in Engineering
2. Guilin University of Electronic Technology
2005 to 2009

Urban System Engineering
Public Transportation Operation & Tech

SKILLS

VISSIM (2 years), Synchro (1 year), vistro, vistro (1 year), HCS (1 year), Autocad (2 years)

CERTIFICATIONS

EIT (Civil Engineer In Training, Maine). Certification No. 6913
EIT (Civil Engineer In Training, Maine). Certification No. 6913

ADDITIONAL INFORMATION

Skills & Expertise

VISSIM, VISTRO, VISUM, Synchro, HCS, AutoCAD, illustrator, ArcMap, Lingo, Lindo, Word,
Excel, PowerPoint, Access, Project Professional, Java, C

