James Lupa P.E.

Senior Electrical Engineer

West Berlin, NJ - Email me on Indeed: indeed.com/r/James-Lupa-P-E/c5c7e5f2dc025a4b

• Professional Electrical Engineer with extensive MEP experience.
•  Over  25  years  of  diversified  consulting  engineer  experience  gained  on  various  municipal,  institutional,
government, commercial, educational and health care projects.
•  Obtained  a  comprehensive  knowledge  and  application  of  NFPA,  NEC  and  IESNA  industry  codes  and
standards while working at MEP consultant companies.
• Skilled in AutoCAD 2012 and MS Office programs.
• Thorough knowledge of the design, construction, and modification requirements for commercial, institutional,
and industrial facilities.
• Performed a diverse selection of professional responsibilities, including various aspects of design, installation,
training and support, as well as project engineering.
• Skilled in cost management and documentation, including one-line diagrams, short circuit studies, project
design criteria, cost estimates, load flow studies, design calculations and specifications for electrical equipment
and systems.

WORK EXPERIENCE

Senior Electrical Engineer
KITCHEN & ASSOCIATES  -  Collingswood, NJ - October 2012 to January 2013

Engineered, designed and specified power, lighting and fire alarm systems for a 250 unit university student
housing project and a charter school renovation.

Senior Electrical Engineer
PSEG NUCLEAR LLC - January 2011 to April 2012

Prepared electrical design modifications for the Salem Generating Station.

Principal Electrical Engineer
TETRA TECH  -  Langhorne, PA - August 2008 to January 2011

Generated proposals, design criteria, specifications, one-line drawings and calculations for utility sized wind
and solar farms.

Senior Electrical Engineer
MARVIN WAXMAN CONSULTING ENGINEERS (MEP)  -  Philadelphia, PA - August 2006 to June 2008

Engineered,  designed  and  specified  new  and  existing  service  entrance  equipment  and  power  distribution
systems for normal and emergency power, lighting, lightning calculations, fire alarm systems.
•  Prepared  electrical  specifications  for,  railroads,  renovated  universities,  commercial  buildings,  high-rise
residential condos, and museums.
• Provided lighting and power design for a refinery marine terminal.
• Performed building electrical systems condition assessments. Completed LEED training.
• Supervised and mentored electrical engineers and designers.

Senior Project Engineer
ALAIMO GROUP (MEP)  -  Mount Holly, NJ - July 2004 to August 2006

Engineered, designed and specified power distribution systems for municipal water and wastewater pump
houses.  Systems  included  backup  emergency  power,  VFD  motor  drives,  building  security  and  fire  alarm
systems.
•  Specified  and  designed  a  unique  high-mast  lighting  security  system  for  the  South  Jersey  Transportation
Authority (SJTA) which included a fiber optic high resolution CCTV system. This is the first time metal halide
lighting was used by SJTA.
• Supervised and mentored electrical designers.

Senior Electrical Engineer
CONCORD ATLANTIC ENGINEERS (MEP)  -  West Atlantic City, NJ - November 1999 to February 2004

Engineered normal and emergency 480V power, lighting and fire alarm systems for new and renovated hotel-
casino expansions, new and renovated high-rise hotels, a 250,000 square foot office building, high-rise condos,
casinos, schools, hospitals and assisted living projects.
• Engineered, designed and specified projects ranging from utility interface with 23kV switchgear to 120/208V
commercial distribution systems including all electrical specifications.

Senior Electrical Engineer
CONCORD ENGINEERING GROUP (MEP)  -  Voorhees, NJ - June 1998 to October 1999

Engineered, designed and specified power distribution ranging from medium voltage switchgear and 480V
substations to 120/208V panelboards, including all electrical specifications.
•  Engineered  service  entrance  equipment,  power  distribution,  lighting  and  fire  alarm  systems  for  schools,
government buildings and assisted living projects. Served as electrical technical expert.
• Supervised and coached electrical designers.

Project Engineer
GIOVANETTI-SCHULMAN ASSOCIATES  -  Drexel Hill, PA - May 1995 to May 1998

Engineered, designed and specified the power distribution system, including 25kV and 5kV switchgear, 480V
substations, normal and emergency power, for major casino expansions including a 400 room high-rise hotel.
• Other major casino expansions included a 600-room high-rise hotel, a 200-room low-rise hotel, office and
apartment building renovation.
•  Prepared  design  development  documents,  manpower  and  cost  estimates,  load  estimates,  short  circuit
studies, electrical systems design (normal and emergency power, fire and security), solved problems during
construction through final testing.
• Supervised and coached electrical designers.

STONE & WEBSTER ENGINEERING CORPORATION, Boston, MA
Electrical Engineer - Power Plants

• Career has included design and engineering on 16 electrical power generating plants.
• The majority of plants were nuclear fueled. Also hydroelectric and fossil fueled plants.
• Developed $20K solutions to $300K problems.
• Multiple assignments for 5 years (combined) on various construction sites resolving electrical equipment,
construction and startup problems.

EDUCATION

Bachelor of Science in Electrical Engineering
Northeastern University - Boston, MA

ADDITIONAL INFORMATION

Licensed Professional Engineer

New Jersey, Pennsylvania and Massachusetts

