Diana Rihawi, Pharm.D

Pharmacist - ACME SAVON PHARMACY

Lansdale, PA - Email me on Indeed: indeed.com/r/8fdd478e9d3c5ada

A highly motivated pharmacist with a broad range of professional skills and experience. A focused team player
and leader with experience managing a retail pharmacy, including communicating with healthcare providers,
counseling patients, training staff and managing inventory. I believe my combination of pharmacy experience
and clinical expertise make a me uniquely qualified professional and someone who will add true value to your
team.

WORK EXPERIENCE

Pharmacist
ACME SAVON PHARMACY  -  Chalfont, PA - June 2012 to Present

Practice drug utilization review and assess order accuracy and appropriateness for individuals.
* Dispense within the framework of federal and state laws as well as employer's policies and procedures.
* Interact with other medical professionals as an integral part of the patient's healthcare team.
* Lead and coordinate pharmacy employees and tasks.
* Market and administer immunizations and clinical services to propel public health.
* Increase profitability and manage inventory to balance operating costs.

Pharmacy Intern
ACME SAVON PHARMACY  -  Bala-Cynwyd, PA - October 2008 to May 2012

Mastered a multitude of pharmacy skills under the supervision of a licensed pharmacist.
* Transliterated oral orders and transcribed prescriptions into Windows-based computer system.
* Compounded and dispensed medicines.
* Provided over-the-counter information and patient counseling, as well as excellent customer service.

EDUCATION

Doctor of Pharmacy
Temple University School of Pharmacy - Philadelphia, PA
2012

SKILLS

Administer Injectables, Team Leadership, Inverntory Management, Extensive Knowledge of Laws, Attention
to Detail, Patient Counseling, Staff Management, Multitasking, Professional Communications, Outstanding
Customer Service

ADDITIONAL INFORMATION

Member of The American Pharmacist Association as well as the Pennsylvania Pharmacist Association

