Matthew Schlemmer, R.Ph, Pharm.D.

Clinical Pharmacist and Pharmacy Manager

Holland, PA - Email me on Indeed: indeed.com/r/71f26ed0dfcd8fcc

Patient-focused  Pharmacist  with  over  twelve  years  of  experience  with  understanding  the  composition  of
medicines, as well as the laws that regulate their manufacture and sale. Displays excellence with upholding the
highest standards of quality patient care and fosters a friendly and cooperative work environment. Maintains
comprehensive  records,  such  as  pharmacy  files,  patient  profiles,  and  registries  of  poisons,  narcotics,  and
controlled drugs. Highly skilled at providing specialized services to help patients manage conditions such as
diabetes, asthma, smoking cessation, or high blood pressure.

• Plan, implement, and maintain procedures for mixing, packaging, and labeling pharmaceuticals, according
to policy and legal requirements, to ensure quality, security, and proper disposal
• Manage pharmacy operations and supervising staff, performing administrative duties, and buying and selling
non-pharmaceutical merchandise
• Assesses the identity, strength and purity of medications, as well as reviews prescriptions to assure accuracy,
to ascertain the needed ingredients, and to evaluate their suitability
•  Provides  accurate  information  regarding  drug  interactions,  side  effects,  dosage  and  proper  medication
storage
•  Analyzes  prescribing  trends  to  monitor  patient  compliance  and  to  prevent  excessive  usage  or  harmful
interactions
• Orders and purchases pharmaceutical supplies, medical supplies, and drugs, maintaining stock and storing
and handling it properly
• Advises customers on the selection of medication brands, medical equipment and health-care supplies
• Collaborates with other health care professionals when needed to plan, monitor, review, and evaluate the
quality and effectiveness of drugs and drug regimens, providing advice on drug applications and characteristics
• Compounds and dispenses medications as prescribed by doctors by calculating, weighing, measuring, and
mixing ingredients, or oversee these activities
• Manage and supervisor both pharmacists and technicians to understand and achieve company goals and
participate in Kaizen events to improve operation processes.
Authorized to work in the US for any employer

WORK EXPERIENCE

Staff PRN Pharmacist
Sav-On/Acme Pharmacy  -  Newtown, PA - June 2008 to Present

Position  Profile:  Filled  and  processed  over  1,200  prescriptions  per  week  accurately.  Provided  clinical
support to physicians regarding drug therapy. Counseled patients regarding prescription and non-prescription
medications  and  delivery  devices.  Prepared  and  compounded  suspensions,  creams,  ointments  and
suppositories. Provided supervision and comprehensive training for Interns and Technicians. Ordered and
managed prescription drug inventory - including controlled substances and narcotics. Processed and managed
expired drug returns.

Additional Pharmacy Work Experience from 1999 to 2002 Available Upon Request

Pharmacist Supervisor/Manager
Express Scripts, Inc  -  Bensalem, PA - September 2003 to Present

Position Profile: Managed and supervised a staff of over 300 technicians and pharmacists processing nearly 1
million prescriptions monthly. Monitored pharmacist and technician’s performance to maintain company goals
in TAT, cost and quality. Provided assist to the Pharmacist-in-Charge to ensure quality, legal requirements and
security. Participated in Kaizen events to improve operation processes and implemented visual management
to create staff level involvement.

Staff Pharmacist
Express Scripts Inc - East Hanover, NJ - May 1999 to September 2003

Position Profile: Provided guidance for technicians in the interpretation of prescription information. Clarified
missing/illegible prescription information based on MD responses via phone or fax. Verified the prescription
information entered by the Data Entry Technician was accurate to the original prescription. Retrieved and
processed new prescriptions from physician/physician. Compounded and ensured compliance on controlled
and refrigerated medications. Assisted in training other staff pharmacists and technicians transitioning to the
department.

EDUCATION

Doctor of Pharmacy
University of the Sciences in Philadelphia - Philadelphia, PA
1999

SKILLS

DDI Certified Manager

ADDITIONAL INFORMATION

Licensed PA, NJ, NY, DE, AZ, MO, NE and KY Pharmacist. 
Licensed PA Injectable Pharmacist

